{% set name = "datapackage" %}
{% set version = "1.15.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datapackage-{{ version }}.tar.gz
  sha256: 7fe7c17a58bb5fad903209d4f761199569d33cc45aad6d88213a8d8f7b3f7092

build:
  entry_points:
    - datapackage = datapackage.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - six >=1.10
    - click >=6.7
    - chardet >=3.0
    - requests >=2.8
    - jsonschema >=2.5
    - unicodecsv >=0.14
    - jsonpointer >=1.10
    - tableschema >=1.20.4
    - dataflows-tabulator >=1.29

test:
  imports:
    - datapackage
  commands:
    - pip check
    - datapackage --help
  requires:
    - pylama
    - tox
    - pip

about:
  home: https://github.com/frictionlessdata/datapackage-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Utilities to work with Data Packages as defined on specs.frictionlessdata.io

extra:
  recipe-maintainers:
    - ocefpaf
    - roll
