{% set version = "1.13.1" %}

package:
  name: datapackage
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/datapackage/datapackage-{{ version }}.tar.gz
  sha256: 89bdd4dfb096589748891e832fa5dbf3798e3dad4fb563229170c180e7d22307

build:
  number: 0
  noarch: python
  entry_points:
    - datapackage = datapackage.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cchardet >=1.0
    - click >=6.7
    - jsonpointer >=1.10
    - jsonschema >=2.5
    - requests >=2.8
    - six >=1.10
    - tableschema >=1.1.0
    - tabulator >=1.24.2
    - unicodecsv >=0.14

test:
  imports:
    - datapackage
  commands:
    - pip check
    - datapackage --help
  requires:
    - pylama
    - tox
    - pip

about:
  home: https://github.com/frictionlessdata/datapackage-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Utilities to work with Data Packages as defined on specs.frictionlessdata.io

extra:
  recipe-maintainers:
    - ocefpaf
    - roll
