{% set version = "1.10.1" %}

package:
  name: datapackage
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/datapackage/datapackage-{{ version }}.tar.gz
  sha256: 1d6cb743c680814b7b5d6dc4fba3be226c437c95284a5984d6311f56379e3237

build:
  number: 0
  noarch: python
  entry_points:
    - datapackage = datapackage.__main__:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cchardet >=1.0
    - click >=6.7
    - jsonpointer >=1.10
    - jsonschema >=2.5
    - requests >=2.8
    - six >=1.10
    - tableschema >=1.1.0
    - tabulator >=1.24.2
    - unicodecsv >=0.14

test:
  imports:
    - datapackage
  commands:
    - datapackage --help
  requires:
    - pylama
    - tox

about:
  home: https://github.com/frictionlessdata/datapackage-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Utilities to work with Data Packages as defined on specs.frictionlessdata.io

extra:
  recipe-maintainers:
    - ocefpaf
    - roll
